// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: matches.sql

package db

import (
	"context"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    fixture_id,
    current_minute,
    current_half,
    home_score,
    away_score,
    active_zone,
    home_attacking_direction
)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, fixture_id, current_minute, current_half, home_score, away_score, active_zone, home_attacking_direction, created_at, updated_at
`

type CreateMatchParams struct {
	FixtureID              int64 `json:"fixture_id"`
	CurrentMinute          int64 `json:"current_minute"`
	CurrentHalf            int64 `json:"current_half"`
	HomeScore              int64 `json:"home_score"`
	AwayScore              int64 `json:"away_score"`
	ActiveZone             int64 `json:"active_zone"`
	HomeAttackingDirection int64 `json:"home_attacking_direction"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.FixtureID,
		arg.CurrentMinute,
		arg.CurrentHalf,
		arg.HomeScore,
		arg.AwayScore,
		arg.ActiveZone,
		arg.HomeAttackingDirection,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CurrentMinute,
		&i.CurrentHalf,
		&i.HomeScore,
		&i.AwayScore,
		&i.ActiveZone,
		&i.HomeAttackingDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches WHERE id = ?
`

func (q *Queries) DeleteMatch(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMatch, id)
	return err
}

const getMatchByFixtureID = `-- name: GetMatchByFixtureID :one
SELECT id, fixture_id, current_minute, current_half, home_score, away_score, active_zone, home_attacking_direction, created_at, updated_at FROM matches WHERE fixture_id = ? LIMIT 1
`

func (q *Queries) GetMatchByFixtureID(ctx context.Context, fixtureID int64) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByFixtureID, fixtureID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CurrentMinute,
		&i.CurrentHalf,
		&i.HomeScore,
		&i.AwayScore,
		&i.ActiveZone,
		&i.HomeAttackingDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, fixture_id, current_minute, current_half, home_score, away_score, active_zone, home_attacking_direction, created_at, updated_at FROM matches WHERE id = ? LIMIT 1
`

func (q *Queries) GetMatchByID(ctx context.Context, id int64) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.FixtureID,
		&i.CurrentMinute,
		&i.CurrentHalf,
		&i.HomeScore,
		&i.AwayScore,
		&i.ActiveZone,
		&i.HomeAttackingDirection,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMatch = `-- name: UpdateMatch :exec
UPDATE matches
SET current_minute = ?,
    current_half = ?,
    home_score = ?,
    away_score = ?,
    active_zone = ?,
    home_attacking_direction = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMatchParams struct {
	CurrentMinute          int64 `json:"current_minute"`
	CurrentHalf            int64 `json:"current_half"`
	HomeScore              int64 `json:"home_score"`
	AwayScore              int64 `json:"away_score"`
	ActiveZone             int64 `json:"active_zone"`
	HomeAttackingDirection int64 `json:"home_attacking_direction"`
	ID                     int64 `json:"id"`
}

func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) error {
	_, err := q.db.ExecContext(ctx, updateMatch,
		arg.CurrentMinute,
		arg.CurrentHalf,
		arg.HomeScore,
		arg.AwayScore,
		arg.ActiveZone,
		arg.HomeAttackingDirection,
		arg.ID,
	)
	return err
}
