// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type Club struct {
	ID              int64        `json:"id"`
	Name            string       `json:"name"`
	Strength        int64        `json:"strength"`
	BackgroundColor string       `json:"background_color"`
	ForegroundColor string       `json:"foreground_color"`
	CreatedAt       sql.NullTime `json:"created_at"`
}

type Fixture struct {
	ID         int64        `json:"id"`
	Gameweek   int64        `json:"gameweek"`
	HomeTeamID int64        `json:"home_team_id"`
	AwayTeamID int64        `json:"away_team_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type Match struct {
	ID                     int64        `json:"id"`
	FixtureID              int64        `json:"fixture_id"`
	CurrentMinute          int64        `json:"current_minute"`
	CurrentHalf            int64        `json:"current_half"`
	HomeScore              int64        `json:"home_score"`
	AwayScore              int64        `json:"away_score"`
	ActiveZone             int64        `json:"active_zone"`
	HomeAttackingDirection int64        `json:"home_attacking_direction"`
	IsCompleted            int64        `json:"is_completed"`
	CompletedAt            sql.NullTime `json:"completed_at"`
	CreatedAt              sql.NullTime `json:"created_at"`
	UpdatedAt              sql.NullTime `json:"updated_at"`
}

type MatchEvent struct {
	ID         int64          `json:"id"`
	MatchID    int64          `json:"match_id"`
	EventType  int64          `json:"event_type"`
	Minute     int64          `json:"minute"`
	TeamSide   string         `json:"team_side"`
	PlayerName sql.NullString `json:"player_name"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Player struct {
	ID        int64        `json:"id"`
	ClubID    int64        `json:"club_id"`
	Name      string       `json:"name"`
	Quality   int64        `json:"quality"`
	CreatedAt sql.NullTime `json:"created_at"`
}
